title: Sydni Liotta
logo: /assets/img/headshot_circle.png
description: Registered dietitian and data analyst with 5+ years of experience in analyzing complex data to drive insights and improve patient outcomes. 
             Skilled in SQL, Power BI, and Tableau, with expertise in healthcare data visualization, trend analysis, and process optimization. 
theme: jekyll-theme-minimal
